### ISSUE TITLE
Group create issues

### ISSUE THREAD

**Issue by dflamand** [dflamand/GroupMeet#10]
The add users thing on the create group page, looks broken for me on Firefox. It doesn't show any users and is just a thin box. This should include a screenshot of the issue.
![screen shot 2016-11-05 at 10 07 51 pm](https://cloud.githubusercontent.com/assets/16523102/20035509/5b040a70-a3a4-11e6-8c60-5ddddde2d4c0.png)

**Comment by Bjorn576** [comment]
Do you have any users created besides the current user? If that's the case, I guess I'll add a check for 'none besides current user' and remove the box if that's the case.
