### ISSUE TITLE
Firefox map issues

### ISSUE THREAD

**Issue by dflamand** [dflamand/GroupMeet#20]
The markers are not in the correct locations, there is a map loading issue on the bottom, and when the map is moved the markers move as well. Screenshot of the issue should be included.
![screen shot 2016-11-06 at 7 58 11 pm](https://cloud.githubusercontent.com/assets/16523102/20046148/a1dc70f6-a45b-11e6-873d-df7d3f9da41d.png)

**Comment by dansiemens** [comment]
Fixed on merged pull request #21
