### ISSUE TITLE
Map Issues

### ISSUE THREAD

**Issue by ckw27** [dflamand/GroupMeet#39]
Submit button is not responding to some inputs
(chrome)
(safari)

Map wouldn’t show occasionally, requires a few refresh page to fix it
(chrome)

**Comment by dansiemens** [comment]
Hey @ErikPontifex, I'm thinking that if the map calculations fail, we should have a modal popup to tell the user why the map isn't calculating (ex. "Could not find address for '...'"). What are your thoughts? I can implement this Monday morning.

**Comment by dansiemens** [comment]
fix: obtain long/lat at autocomplete time. if long/lat is empty (if user did not use the autocomplete), then re-query the places api for the geometry. see http://stackoverflow.com/questions/13478646/google-map-api-get-latitude-and-longitude-from-autocomplete-without-map

**Comment by dansiemens** [comment]
Fixed.
