### ISSUE TITLE
Page stylings

### ISSUE THREAD

**Issue by dflamand** [dflamand/GroupMeet#8]
Style the user profile page, group create, and group page. Group page would need the map integration.

**Comment by ErikPontifex** [comment]
Let's leave the group/map integration for next time. I have a better idea for the group workflow and it's getting too close to the deadline as it is. For the first iteration, users will be able to create groups,  see who belongs to their created groups, and that's pretty much going to be it. 

I'll work on basic styling for the user profile, group creation and group pages for now.

**Comment by ErikPontifex** [comment]
I added basic styling to the user profile, group create, and group show pages.
